name: Build Aria2c

on:
  workflow_dispatch:
  push:
    tags:
      - aria2c-release-*.*.*

jobs:
  build-windows:
    name: Build for Windows (${{ matrix.arch }})
    runs-on: ubuntu-latest
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
      # libssh2_path: "${{ github.workspace }}/libssh2-windows-arm64"
      # VCPKG_DEFAULT_TRIPLET: "${{ matrix.arch }}-windows-static"

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "arm64"
          - arch: "x64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            build-essential cmake ninja-build pkg-config p7zip autoconf automake libtool autopoint libxml2-dev libcppunit-dev autotools-dev
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64.tar.xz
          tar -xf llvm-mingw-*.tar.xz
          mv llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64 llvm-mingw
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: Install libraries from vcpkg
        run: |
          PATH=$PATH:${{ env.llvm_path }}/bin
          cd vcpkg
          git apply ${{ github.workspace }}/patches/vcpkg-disable-asm-for-arm32.patch
          # tell vcpkg to only build Release variants of the dependencies
          mkdir triplets_overlay
          cp triplets/community/${{ matrix.arch }}-mingw-static.cmake triplets_overlay/${{ matrix.arch }}-mingw-static-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/${{ matrix.arch }}-mingw-static-release.cmake

          # clear buildtrees after each package installation to reduce disk space requirements
          packages="zlib expat sqlite3 c-ares gmp"
          ./vcpkg upgrade \
            --overlay-triplets=triplets_overlay \
            --no-dry-run

          ./vcpkg install \
            --overlay-triplets=triplets_overlay \
            --clean-after-build \
            --triplet=${{ matrix.arch }}-mingw-static-release \
            $packages

      - name: Build aria2
        run: |
          chmod 755 ./scripts/aria2c_build_win.sh
          ./scripts/aria2c_build_win.sh ${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-windows-${{ matrix.arch }}
          path: aria2*.zip

  build-macos:
    name: Build for macOS
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools and dependencies
        run: |
          brew install automake autoconf libtool pkg-config gettext p7zip
          brew install gmp libssh2 c-ares sqlite3 zlib expat

      # - name: Import Code-Signing Certificate
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: apple-actions/import-codesign-certs@v2
      #   with:
      #     p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
      #     p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Build aria2
        # env:
        # APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        # APPLE_ID: ${{ secrets.APPLE_ID }}
        # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          chmod +x ./scripts/aria2c_build_mac.sh
          ./scripts/aria2c_build_mac.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-macos-arm64
          path: aria2*.zip

  build-linux:
    name: Build for Linux (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "x86_64"
            os: ubuntu-22.04
          - arch: "arm64"
            os: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build aria2
        run: |
          chmod +x ./scripts/aria2c_build_linux.sh
          ./scripts/aria2c_build_linux.sh ${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aria2-linux-${{ matrix.arch }}
          path: aria2*.zip

  release:
    name: Release
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/aria2c-release-')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List files
        run: ls -R artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: artifacts/**/*.zip

  release-update:
    runs-on: ubuntu-latest
    needs: [release]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release engine version file
        run: pnpm build-engine-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
